### ISSUE TITLE
对Trash的疑问

### ISSUE THREAD

**Issue by mattshma** [mattshma/hadoop-practice#1]
Hadoop每个目录中将文件删除后，会放在对应用户(/`user/hadoop`)下的.Trash目录中。但输入命令`rm -r /user/username/.Trash`目录时，该Trash中的文件会放到`hdfs://${nameserivce}/user/hdfs/.Trash`目录中，使用-skipTrash可跳过`${nameservice}`的.Trash目录。

疑问：
删除文件要删除两次Trash？

**Comment by beitian** [comment]
测试了下。如下

```
root@db20-059:~# HADOOP_USER_NAME=hdfs hdfs dfs -rm /user/hadoop/xiaofei/parted_disk.sh
Moved: 'hdfs://nameservice1/user/hadoop/xiaofei/parted_disk.sh' to trash at: hdfs://nameservice1/user/hdfs/.Trash/Current
```

即删除的文件直接在 `hdfs://nameservice1/user/hdfs/.Trash/Current`，而非`/user/hadoop/.Trash`中。那问题又来了，`/user/hadoop/.Trash`中的文件是怎么来的？

**Comment by mattshma** [comment]
因为用户不同导致出现的这个问题，使用hdfs删除hadoop用户的回收站，文件会被删除到hdfs的回收站中。使用hadoop用户删除hadoop的回收站，文件才会被直接删除。
